version: '3.8'

services:
  c:
    container_name: switchback_c
    image: switchback-c:latest
    build:
      context: ../../..
      dockerfile: examples/recipes/c/Dockerfile
    ports:
      - "8000:8000"
    # Note: dist/ is NOT mounted - it's baked into the image
    # For development with hot reload, build locally and uncomment:
    # volumes:
    #   - ./dist:/app/dist:ro
